global:
  prefix: '!'
  sayformat: '&b[{world}]&f {sender}:&f {message}'
  meformat: '&b[{world}] &d*&f {sender} {message}'
world:
  prefix: '#'
  sayformat: '&a[{prefix}]&f {sender}:&f {message}'
  meformat: '&a[{prefix}] &d*&f {sender} {message}'
  default: true
admin:
  prefix: '@'
  sayformat: '&4[{prefix}]&f {sender}:&f {message}'
  meformat: '&4[{prefix}] &d*&f {sender} {message}'
staff:
  prefix: '^'
  sayformat: '&5[{prefix}]&f {sender}:&f {message}'
  meformat: '&5[{prefix}] &d*&f {sender} {message}'
party:
  prefix: '$'
  cost: 0
  sayformat: '&d[{party}]&f {sender}:&f {message}'
  meformat: '&d[{party}] *&f {sender} {message}'
local:
  prefix: '%'
  radius: 64
  sayformat: '<{sender}&r> {message}'
  meformat: '&d*&f {sender} {message}'
version: 1.5
emote:
  prefix: '|'
default: '!'
