name: KitsuneChat
version: 1.4.3
main: me.cyberkitsune.prefixchat.KitsuneChat
softdepend: [Vault]
commands:
     kc:
      description: KitsuneChat commands.
     me:
      description: Emote
      
permissions:
     kitsunechat.adminchat:
        description: Allows use of adminchat
        default: op
     kitsunechat.nodefault.global:
        description: Denies use of using /kc to default to global chat.
        default: false
     kitsunechat.nodefault.world:
        description: Denies use of using /kc to default to world chat.
        default: false
     kitsunechat.nodefault.party:
        description: Denies use of using /kc to default to party chat.
        default: false
     