name: KitsuneChat
version: 1.3.1
main: com.cyberkitsune.prefixchat.KitsuneChat
commands:
     kc:
      description: KitsuneChat commands.
     me:
      description: Emote
      
permissions:
     kitsunechat.adminchat:
        description: Allows use of adminchat
        default: op