name: KitsuneChat
version: 1.6.1-SNAPSHOT
main: me.cyberkitsune.prefixchat.KitsuneChat
authors: [CyberKitsune, Alynna]
softdepend: [Vault, Multiverse-Core]
commands:
     kc:
      description: KitsuneChat commands.
     me:
      description: Preform an action in text.
     msg:
      description: Send a private message.
     r:
      description: Reply to a message in chat.
      
permissions:
     kitsunechat.adminchat:
        description: Allows use of adminchat
        default: op
     kitsunechat.staffchat:
        description: Allows the use of staff chat.
        default: op
     kitsunechat.nodefault.*:
        description: Deny ALL the chat!
        default: false
        children:
           kitsunechat.nodefault.global: true
           kitsunechat.nodefault.world: true
           kitsunechat.nodefault.party: true
     kitsunechat.nodefault.global:
        description: Denies use of using /kc to default to global chat.
        default: false
     kitsunechat.nodefault.world:
        description: Denies use of using /kc to default to world chat.
        default: false
     kitsunechat.nodefault.party:
        description: Denies use of using /kc to default to party chat.
        default: false
     