name: KitsuneChat
version: 0.2
main: com.cyberkitsune.prefixchat.KitsuneChat
commands:
     ch:
      description: Change KitsuneChat channel.
      
permissions:
     kitsunechat.adminchat:
        description: Allows use of adminchat
        default: op