name: KitsuneChat
version: 1.2
main: com.cyberkitsune.prefixchat.KitsuneChat
commands:
     kc:
      description: KitsuneChat commands.
      
permissions:
     kitsunechat.adminchat:
        description: Allows use of adminchat
        default: op